blank_issues_enabled: true
contact_links:
  - name: Security issue (private)
    about: Please report security vulnerabilities privately.
    url: https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities
